"""empty message

Revision ID: 25f36a4993ba
Revises: c642a8623bf9
Create Date: 2021-09-17 11:05:41.788266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25f36a4993ba'
down_revision = 'c642a8623bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_country_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_country_id_fkey', 'user', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###
