"""empty message

Revision ID: c642a8623bf9
Revises: f58b64fd4560
Create Date: 2021-09-15 17:03:53.936060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c642a8623bf9'
down_revision = 'f58b64fd4560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('country_id', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    op.create_foreign_key(None, 'user', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'city_id')
    op.drop_column('user', 'country_id')
    op.drop_column('user', 'name')
    op.drop_table('city')
    op.drop_table('country')
    # ### end Alembic commands ###
